validate:
  image: gramener/builderrors
  script: builderrors --skip=prettier --skip=eslint

deploy:
  stage: deploy
  script: deploy
  variables:
    SERVER: gramener.com
    URL: financedatacomparison
    VERSION: static
    # SETUP: npm install --production
    CORS: enabled
  environment:
    name: production
    url: https://gramener.com/financedatacomparison/
